const categoriesList = [
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'art', label: 'Art' },
  { value: 'anime', label: 'Anime' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'aviation', label: 'Aviation' },
  { value: 'awards', label: 'Awards' },
  { value: 'business', label: 'Business' },
  { value: 'charity', label: 'Charity' },
  { value: 'comedy', label: 'Comedy' },
  { value: 'career', label: 'Career' },
  { value: 'community', label: 'Community' },
  { value: 'competition', label: 'Competition' },
  { value: 'conference', label: 'Conference' },
  { value: 'cultural ', label: 'Cultural ' },
  { value: 'dance', label: 'Dance' },
  { value: 'design', label: 'Design' },
  { value: 'fashion', label: 'Fashion' },
  { value: 'beauty', label: 'Beauty' },
  { value: 'travel', label: 'Travel' },
  { value: 'nature', label: 'Nature' },
  { value: 'lifestyle', label: 'Lifestyle' },
  { value: 'economics', label: 'Economics' },
  { value: 'education', label: 'Education' },
  { value: 'entertainment', label: 'Entertainment' },
  { value: 'environmental', label: 'Environmental' },
  { value: 'exhibition', label: 'Exhibition' },
  { value: 'expo', label: 'Expo' },
  { value: 'festival', label: 'Festival' },
  { value: 'finance', label: 'Finance', related: 'investing' },
  { value: 'fitness', label: 'Fitness' },
  { value: 'foodanddrinks', label: 'Food and Drinks' },
  { value: 'fundraiser', label: 'Fundraiser' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'nightlife', label: 'Nightlife' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'healthandfitness', label: 'Health and Fitness' },
  { value: 'historical', label: 'Historical' },
  { value: 'holiday', label: 'Holiday' },
  { value: 'international', label: 'International' },
  { value: 'livestream', label: 'Live Stream' },
  { value: 'manufacturing', label: 'Manufacturing' },
  { value: 'marathon', label: 'Marathon' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'meetup', label: 'Meet up' },
  { value: 'music', label: 'Music' },
  { value: 'networking', label: 'Networking' },
  { value: 'party', label: 'Party' },
  { value: 'performingarts', label: 'Performing arts' },
  { value: 'politics', label: 'Politics' },
  { value: 'productlaunch', label: 'Product Launch' },
  { value: 'protest', label: 'Protest' },
  { value: 'racing', label: 'Racing' },
  { value: 'religion', label: 'Religion' },
  { value: 'running', label: 'running' },
  { value: 'sales', label: 'Sales' },
  { value: 'seminar', label: 'Seminar' },
  { value: 'showcase', label: 'Showcase' },
  { value: 'singing', label: 'Singing' },
  { value: 'sports', label: 'Sports' },
  { value: 'technology', label: 'Technology' },
  { value: 'tournament', label: 'Tournament' },
  { value: 'tradeshow', label: 'Trade Show' },
  { value: 'training', label: 'Training' },
  { value: 'science', label: 'Science' },
  { value: 'webinar', label: 'Webinar' },
  { value: 'wedding', label: 'Wedding' },
  { value: 'workshop', label: 'Workshop' },
  { value: 'writing', label: 'Writing' }
]

export default categoriesList
