const southAfricanCities = [
  'Alberton',
  'Alice',
  'Alrode',
  'Amanzimtoti',
  'Ashton',
  'Atlantis',
  'Balfour',
  'Bathurst',
  'Beaufort West',
  'Bedfordview',
  'Belhar',
  'Bellville',
  'Benoni',
  'Bergvliet',
  'Bethal',
  'Bethlehem',
  'Bloemfontein',
  'Boksburg',
  'Bothasig',
  'Botshabelo',
  'Braamfontein',
  'Brackenfell',
  'Brakpan',
  'Bredasdorp',
  'Brits',
  'Bronkhorstspruit',
  'Brooklyn',
  'Bryanston',
  'Buffalo',
  'Butterworth',
  'Cape Town',
  'Capital Park',
  'Carletonville',
  'Carolina',
  'Centurion',
  'City of Cape Town',
  'Clanwilliam',
  'Claremont',
  'Coega',
  'Coligny',
  'Constantia',
  'Craighall',
  'Cullinan',
  'De Aar',
  'Delmas',
  'Deneysville',
  'Despatch',
  'Doornfontein',
  'Dube Location',
  'Duiwelskloof',
  'Dullstroom',
  'Dundee',
  'Durban',
  'Durbanville',
  'East London',
  'Edenburg',
  'Edenvale',
  'Eersterivier',
  'Elandsfontein',
  'Elarduspark',
  'Eloff',
  'Elsburg',
  'Elsenburg',
  'Emerald Hill',
  'Emnambithi-Ladysmith',
  'Empangeni',
  'Erasmia',
  'Ermelo',
  'Eshowe',
  'Evander',
  'Faure',
  'Florida Glen',
  'Fochville',
  'Fordsburg',
  'Fort Cox',
  'Franschhoek',
  'Gansbaai',
  'Ganspan',
  'George',
  'Germiston',
  'Gezina',
  'Gillitts',
  'Gingindlovu',
  'Glen Austin',
  'Goodwood',
  'Graaff Reinet',
  'Grabouw',
  'Grahamstown',
  'Greytown',
  'Groblersdal',
  'Haenertsburg',
  'Harrismith',
  'Hartbeespoort',
  'Hartenbos',
  'Hartswater',
  'Hatfield',
  'Hawston',
  'Hazyview',
  'Heidelberg',
  'Hekpoort',
  'Henley on Klip',
  'Hennenman',
  'Hermanus',
  'Hillcrest',
  'Hilton',
  'Himeville',
  'Hluhluwe',
  'Hoedspruit',
  'Hogsback',
  'Houghton Estate',
  'Hout Bay',
  'Howick',
  'Humansdorp',
  'Hyde Park',
  'Irene',
  'Isando',
  'Ixopo',
  'Johannesburg',
  'Kalkbaai',
  'Katlehong',
  'Kempton Park',
  'Kimberley',
  'Kingsborough',
  'Kingsley',
  'Kingsmead',
  'Kinross',
  'Kleinmond',
  'Klerksdorp',
  'Kloof',
  'Knysna',
  'Kokstad',
  'Kraaifontein',
  'Kranskop',
  'Kriel',
  'Kroonstad',
  'Krugersdorp',
  'Kuils River',
  'KwaDukuza',
  'La Lucia',
  'La Motte',
  'Ladybrand',
  'Lansdowne',
  'Laudium',
  'Lephalale',
  'Lichtenburg',
  'Lombardy East',
  'London',
  'Louis Trichardt',
  'Lutzville',
  'Lydenburg',
  'Lyndhurst',
  'Lynnwood',
  'Lyttelton',
  'Machadodorp',
  'Mafikeng',
  'Maidstone',
  'Majuba',
  'Malmesbury',
  'Malvern',
  'Maraisburg',
  'Margate',
  'Marshalltown',
  'Meadowridge',
  'Medunsa',
  'Melkbosstrand',
  'Merrivale',
  'Messina',
  'Meyerton',
  'Middelburg',
  'Midrand',
  'Milnerton',
  'Mmabatho',
  'Mobeni',
  'Modderfontein',
  'Mokopane',
  'Montagu',
  'Monument Park',
  'Mooi River',
  'Mookgophong',
  'Moorreesburg',
  'Morningside Manor',
  'Mossel Bay',
  'Mount Edgecombe',
  'Mthatha',
  'Muizenberg',
  'Napier',
  'Nelspruit',
  'New Germany',
  'Newcastle',
  'Newlands',
  'Nigel',
  'Northcliff',
  'Odendaalsrus',
  'Ogies',
  'Olifantsfontein',
  'Onderstepoort',
  'Onverwacht',
  'Oranjeville',
  'Oranjezicht',
  'Ottosdal',
  'Oudtshoorn',
  'Overport',
  'Paarl',
  'Panorama',
  'Parktown',
  'Parkview',
  'Parow',
  'Peninsula',
  'Phalaborwa',
  'Philadelphia',
  'Philipstown',
  'Phoenix',
  'Phokeng',
  'Pietermaritzburg',
  'Pinelands',
  'Pinetown',
  'Plettenberg Bay',
  'Plumstead',
  'Polokwane',
  'Pongola',
  'Port Alfred',
  'Port Elizabeth',
  'Port Shepstone',
  'Potchefstroom',
  'Pretoria',
  'Prieska',
  'Primrose',
  'Pringle Bay',
  'Queensburgh',
  'Queenstown',
  'Queenswood',
  'Randburg',
  'Randfontein',
  'Rawsonville',
  'Rhodes',
  'Richards Bay',
  'Richmond',
  'Riebeek-Kasteel',
  'Rivonia',
  'Roggebaai',
  'Roodepoort',
  'Rooigrond',
  'Rooihuiskraal',
  'Rosebank',
  'Rosettenville',
  'Rosslyn',
  'Rustenburg',
  'Sabie',
  'Saint Helena Bay',
  'Saint James',
  'Saldanha',
  'Salt Rock',
  'Sandown',
  'Sandton',
  'Sasolburg',
  'Schweizer-Reneke',
  'Scottburgh',
  'Sebokeng',
  'Secunda',
  'Sedgefield',
  'Senekal',
  'Shelly Beach',
  'Silverton',
  'Sinoville',
  'Somerset West',
  'Soshanguve',
  'Soweto',
  'Springs',
  'Standerton',
  'Stanford',
  'Stellenbosch',
  'Stilfontein',
  'Strand',
  'Sun Valley',
  'Swartkops',
  'Temba',
  'Tembisa',
  'Thabazimbi',
  'The Rest',
  'Thohoyandou',
  'Three Anchor Bay',
  'Three Rivers',
  'Tokai',
  'Tongaat',
  'Tzaneen',
  'Uitenhage',
  'Umbogintwini',
  'Umdloti',
  'Umhlanga',
  'Umkomaas',
  'Umtentweni',
  'Upington',
  'Vaalbank',
  'Vaalpark',
  'Vanderbijlpark',
  'Vereeniging',
  'Verulam',
  'Villiersdorp',
  'Virginia',
  'Vosloorus',
  'Vrededorp',
  'Vredenburg',
  'Vryheid',
  'Walkerville',
  'Walmer Heights',
  'Warner Beach',
  'Wartburg',
  'Waverley',
  'Welgelegen',
  'Welgemoed',
  'Welkom',
  'Wellington',
  'Weltevreden',
  'Weltevreedenpark',
  'Westonaria',
  'Westville',
  'White River',
  'Wilderness',
  'Winterton',
  'Witbank',
  'Witpoortjie',
  'Wonderboom',
  'Worcester',
  'Wynberg',
  'Zeerust',
  'Adelaide',
  'Alfred Nzo District Municipality',
  'Aliwal North',
  'Amathole District Municipality',
  'Bhisho',
  'Buffalo City Metropolitan Municipality',
  'Burgersdorp',
  'Cacadu District Municipality',
  'Chris Hani District Municipality',
  'Cradock',
  'Dordrecht',
  'Elliot',
  'Fort Beaufort',
  'Graaff-Reinet',
  'Ilinge',
  'Joe Gqabi District Municipality',
  'Kirkwood',
  'Kruisfontein',
  'Lady Frere',
  'Molteno',
  'Nelson Mandela Bay Metropolitan Municipality',
  'OR Tambo District Municipality',
  'Port Saint John’s',
  'Queensdale',
  'Somerset East',
  'Stutterheim',
  'Whittlesea',
  'Willowmore',
  'Allanridge',
  'Bothaville',
  'Brandfort',
  'Clocolan',
  'Fezile Dabi District Municipality',
  'Frankfort',
  'Heilbron',
  'Hoopstad',
  'Koppies',
  'Kutloanong',
  'Lejweleputswa District Municipality',
  'Lindley',
  'Mangaung Metropolitan Municipality',
  'Marquard',
  'Parys',
  'Phuthaditjhaba',
  'Reitz',
  'Thaba Nchu',
  'Thabo Mofutsanyana District Municipality',
  'Theunissen',
  'Ventersburg',
  'Viljoenskroon',
  'Villiers',
  'Vrede',
  'Vredefort',
  'Wesselsbron',
  'Winburg',
  'Xhariep District Municipality',
  'Zastron',
  'City of Johannesburg Metropolitan Municipality',
  'City of Tshwane Metropolitan Municipality',
  'Diepsloot',
  'Eastleigh',
  'Eden Glen',
  'Eden Glen Ext 60',
  'Ekangala',
  'Ekurhuleni Metropolitan Municipality',
  'Mabopane',
  'Midstream',
  'Muldersdriseloop',
  'Orange Farm',
  'Sedibeng District Municipality',
  'West Rand District Municipality',
  'Amajuba District Municipality',
  'Ballito',
  'Berea',
  'Ekuvukeni',
  'eMkhomazi',
  'eSikhaleni',
  'eThekwini Metropolitan Municipality',
  'Glencoe',
  'iLembe District Municipality',
  'Mondlo',
  'Mooirivier',
  'Mpophomeni',
  'Mpumalanga',
  'Mtubatuba',
  'Ndwedwe',
  'Sisonke District Municipality',
  'Sundumbili',
  'Ugu District Municipality',
  'Ulundi',
  'uMgungundlovu District Municipality',
  'uMkhanyakude District Municipality',
  'uMzinyathi District Municipality',
  'uThukela District Municipality',
  'uThungulu District Municipality',
  'Utrecht',
  'Zululand District Municipality',
  'Bochum',
  'Capricorn District Municipality',
  'Ga-Kgapane',
  'Giyani',
  'Lebowakgomo',
  'Mankoeng',
  'Modimolle',
  'Mopani District Municipality',
  'Musina',
  'Nkowakowa',
  'Sekhukhune District Municipality',
  'Thulamahashi',
  'Vhembe District Municipality',
  'Warmbaths',
  'Waterberg District Municipality',
  'Barberton',
  'Belfast',
  'Breyten',
  'Driefontein',
  'Ehlanzeni District',
  'eMbalenhle',
  'Gert Sibande District Municipality',
  'Hendrina',
  'Komatipoort',
  'Nkangala District Municipality',
  'Piet Retief',
  'Siyabuswa',
  'Volksrust',
  'Bloemhof',
  'Bojanala Platinum District Municipality',
  'Christiana',
  'Dr Kenneth Kaunda District Municipality',
  'Dr Ruth Segomotsi Mompati District Municipality',
  'Ga-Rankuwa',
  'Jan Kempdorp',
  'Koster',
  'Mahikeng',
  'Maile',
  'Ngaka Modiri Molema District Municipality',
  'Orkney',
  'Vryburg',
  'Wolmaransstad',
  'Barkly West',
  'Brandvlei',
  'Calvinia',
  'Carnarvon',
  'Colesberg',
  'Daniëlskuil',
  'Frances Baard District Municipality',
  'Fraserburg',
  'John Taolo Gaetsewe District Municipality',
  'Kathu',
  'Kenhardt',
  'Kuruman',
  'Namakwa District Municipality',
  'Noupoort',
  'Orania',
  'Pampierstad',
  'Pixley ka Seme District Municipality',
  'Pofadder',
  'Postmasburg',
  'Ritchie',
  'Siyanda District Municipality',
  'Springbok',
  'Van Wyksvlei',
  'Warrenton',
  'Albertina',
  'Arniston',
  'Caledon',
  'Calitzdorp',
  'Cape Winelands District Municipality',
  'Central Karoo District Municipality',
  'Ceres',
  'De Rust',
  'Eden District Municipality',
  'Hardys Memories of Africa',
  'Ladismith',
  'Overberg District Municipality',
  'Piketberg',
  'Prince Albert',
  'Retreat',
  'Riversdale',
  'Robertson',
  'Rondebosch',
  'Sunset Beach',
  'Swellendam',
  'Vredendal',
  'West Coast District Municipality',
  'Zoar'
]
